version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: my_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  spring-boot-app:
    build: .
    container_name: s-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_db
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: pass
